name: ci-yuki

on:
  push:
    branches:
      - main
jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.0.0

      - name: Install & Build
        run: | 
          yarn config set registry https://registry.npm.taobao.org/
          yarn install 
          yarn build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # scp参数
          ARGS: "-avzr --delete"
          # 源目录
          SOURCE: "dist"
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: "49.232.132.226"
          # 用户
          REMOTE_USER: "root"
          # 目标地址
          TARGET: "/root/vue-in-action"
